#!/bin/sh
set -e

# Usage: ./cc out.o in.c extra-args...
[ -z "$2" ] && {
  echo >&2 "$0: usage: out.o in.c extra-args..."
  exit 2
}

OUT="$1"
IN="$2"
shift
shift

## Ensure that we get unwrapped clang on NixOS.
CLANGVER=$(clang --version|head -n 1|sed 's/^.*version \([0-9]*\.[0-9]\).*$/\1/')
CLANG=clang
which "clang-$CLANGVER" >/dev/null 2>/dev/null && CLANG="clang-$CLANGVER"

## Compile.
"$CLANG" -cc1 \
  -triple thumbv7m-v7m-unknown \
  -target-cpu cortex-m3 \
  -emit-llvm \
  -Oz "$@" \
  -o "${OUT}.ll-opt" "$IN"

## Assemble.
llc -o="${OUT}.s" "${OUT}.ll-opt"
llc -o="${OUT}" -filetype=obj "${OUT}.ll-opt"
