#!/bin/sh
set -e

# Usage: ./cc out.o in.c extra-args...
[ -z "$2" ] && {
  echo >&2 "$0: usage: out.o in.c extra-args..."
  exit 2
}

OUT="$1"
IN="$2"
shift
shift

## Ensure that we get unwrapped clang on NixOS.
[ -z "$CLANG" ] && {
  CLANG="$(realpath $(which clang))"
  q="$(dirname $(dirname "$CLANG"))/nix-support/orig-cc"
  [ -e "$q" ] && CLANG="$(cat $q)/bin/clang"
}

## Compile.
"$CLANG" -cc1 \
  -triple thumbv7m-v7m-unknown \
  -target-cpu cortex-m3 \
  -nostdsysteminc \
  -emit-llvm \
  -Oz "$@" \
  -o "${OUT}.ll-opt" "$IN"

## Assemble.
llc -o="${OUT}.s" "${OUT}.ll-opt"
llc -o="${OUT}" -filetype=obj "${OUT}.ll-opt"
