#include "otg.h"
#include "otg_common.c"

static uint32_t gS1_chipRev = 0;
uint32_t g_using264BytePagesForNVM = 0;

#ifdef PROPRIETARY
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
#endif

void noreturn S1Start(void) {
#ifdef PROPRIETARY
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
/*               scrubbed                    */
#endif
}

const char gS1_versionString[] = "OTG";

asm(
  ".pushsection .textstart,\"ax\",@progbits\n"
  ".global S1Entrypoint\n"
  ".set noreorder\n"
  "S1Entrypoint:\n"
  "j S1Entrypoint2\n"
  "nop\n"
  ".4byte gS1_versionString\n"
  ".popsection\n"

  ".pushsection .textasm,\"ax\",@progbits\n"
  ".global S1Entrypoint2\n"
  "S1Entrypoint2:\n"
  "la $sp, S1StackTop\n"
  "move $fp, $sp\n"
  "lui $k1, 0xC000\n"
  "jal S1Start\n"
  "nop\n"
  ".popsection\n"
  );

asm(
  ".pushsection .stage2,\"a\",@progbits\n"
  ".global S1CRC\n"
  "S1CRC:\n"
  ".4byte 0xDEADBEEF\n"
  "\n"
  ".global S2Header\n"
  ".set noreorder\n"
  "S2Header:\n"
  ".incbin \"otg_stage2.bin\"\n"
  ".popsection\n"

  ".pushsection .ape,\"a\",@progbits\n"
  ".global APEImageStart\n"
  ".global APEImageEnd\n"
  "APEImageStart:\n"
  ".incbin \"" APE_IMAGE_FN "\"\n"
  "APEImageEnd:\n"
  ".popsection\n"
  );

extern int S1Entrypoint;
extern int S1SizeInWords;
extern int S1TextOffset;
extern int APEImageStartPhys;
extern int APEImageSizeInWordsWithTypeByte;

const __attribute__((section(".header"))) otg_header gS1_otgHeader = {
  .magic         = HEADER_MAGIC,
  .s1Entrypoint  = (uint32_t)&S1Entrypoint,
  .s1Size        = (uint32_t)&S1SizeInWords,
  .s1Offset      = (uint32_t)&S1TextOffset, //sizeof(otg_header),
  .bootHdrCRC    = 0xDEADBEEF,
  .dir           = {
    [0] = {
      .loadAddr = 0x00000007,
      .typeSize = (uint32_t)&APEImageSizeInWordsWithTypeByte,
      /* OTG_HEADER_TAG_TYPE__APE_CODE | APEImageSizeInWordsWithTypeByte,*/
      .offset   = (uint32_t)&APEImageStartPhys,
    },
  },
  .mfrFormatRev = 0x44,
  .dirCRC = 0x00,
  .mfrLen  = 0x008C,
  .mfr2Len = 0x008C,
  .mac0 = { 0x000A, 0xF7A44C84 }, // TODO CHANGE THIS
  .partNo  = "Use 'vpdsecfg'", //"BCM95719",
  .partRev = "A0",
  .fwRev = 0x012D,
  .mfrDate = 0x00000000,
  .pciDevice          = PCI_DEVICE_ID,
  .pciVendor          = PCI_VENDOR_ID,
  .pciSubsystem       = PCI_DEVICE_ID,
  .pciSubsystemVendor = PCI_VENDOR_ID,
  .cpuClock           = 0x0042,
  .ncSMBUSAddr        = 0x64, // NC
  .bmcSMBUSAddr       = 0x00, // BMC?
  .powerDissipated = {0x0A,0x00,0x00,0x64}, // @BC
  .powerConsumed   = {0x0A,0x00,0x00,0x64}, // @C0
  .func0CfgFeature = 0xCDB50282, //Talos=0xC5C00080,
  .func0CfgHW   = 0x00006014, //Talos=0x00004014,
  .func0CfgHW2 = 0x00000042, //Talos=0x00000040,
  .mac1 = { 0x000A, 0xF7A44C85 },
  .func1CfgFeature  = 0xCDB50202, //Talos=0xC5C00000,
  .func1CfgHW       = 0x00006014, //Talos=0x00004014,
  .func1CfgHW2      = 0x00000042, //Talos=0x00000040,
  .func2CfgFeature  = 0xCDB50202, //Talos=0xC5C00000,
  .func2CfgHW       = 0x00006014, //Talos=0x00004014,
  .func2CfgHW2      = 0x00000042, //Talos=0x00000040,
  .func3CfgFeature  = 0xCDB50202, //Talos=0xC5C00000,
  .func3CfgHW       = 0x00006014, //Talos=0x00004014,
  .func3CfgHW2      = 0x00000042, //Talos=0x00000040,
  .cfgShared        = 0x0012AA38, //Talos=0x00C2AA38,
  .powerBudget0     = 0x2C163C2C,
  .powerBudget1     = 0x0000230A,
  .powerBudget2     = 0x00000000,
  .powerBudget3     = 0x00000000,
  .macNVMSize       = 0x0002,
  .cfg5             = 0,
  .pciSubsystemF0GPHY   = PCI_SUBSYSTEM_ID,
  .pciSubsystemF1GPHY   = PCI_SUBSYSTEM_ID,
  .pciSubsystemF2GPHY   = PCI_SUBSYSTEM_ID,
  .pciSubsystemF3GPHY   = PCI_SUBSYSTEM_ID,
  .pciSubsystemF0SERDES = PCI_DEVICE_ID,
  .pciSubsystemF1SERDES = PCI_DEVICE_ID,
  .pciSubsystemF2SERDES = PCI_DEVICE_ID,
  .pciSubsystemF3SERDES = PCI_DEVICE_ID,
  .mac2 = { 0x000A, 0xF7A44C86 },
  .mac3 = { 0x000A, 0xF7A44C87 },
  .vpd = {
    0x82,0x0F,0x00,0x55,0x73,0x65,0x20,0x27,0x76,0x70,0x64,0x73,0x65,0x63,0x66,0x67,
    0x27,0x00,0x90,0x6B,0x00,0x50,0x4E,0x0E,0x55,0x73,0x65,0x20,0x27,0x76,0x70,0x64,
    0x73,0x65,0x63,0x66,0x67,0x27,0x45,0x43,0x09,0x31,0x30,0x36,0x36,0x37,0x39,0x2D,
    0x31,0x35,0x53,0x4E,0x0E,0x55,0x73,0x65,0x20,0x27,0x76,0x70,0x64,0x73,0x65,0x63,
    0x66,0x67,0x27,0x4D,0x4E,0x04,0x31,0x34,0x65,0x34,0x56,0x30,0x0E,0x55,0x73,0x65,
    0x20,0x27,0x76,0x70,0x64,0x73,0x65,0x63,0x66,0x67,0x27,0x52,0x56,0x22,0x09,0x00,
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x91,0x7C,0x00,0x59,0x41,0x0E,0x55,0x73,0x65,0x20,0x27,0x76,0x70,0x64,0x73,0x65,
    0x63,0x66,0x67,0x27,0x56,0x31,0x0E,0x55,0x73,0x65,0x20,0x27,0x76,0x70,0x64,0x73,
    0x65,0x63,0x66,0x67,0x27,0x52,0x57,0x57,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x78},
};
